### ISSUE TITLE
error deploy openflow to kubernetes

### ISSUE THREAD

**Issue by jonsieck** [open-rpa/helm-charts#1]
Hi Skadefro 
I am truing to install the setup to Kubernetes but is stucked inthe install.

I have followed the readme:MD

"helm install openflow openiap/openflow -n demo1 --values ./demo1.yaml"

and returns 
Error: INSTALLATION FAILED: template: openflow/templates/zipkin.yaml:2:18: executing "openflow/templates/zipkin.yaml" at <.Values.openflow.license_key>: nil pointer evaluating interface {}.license_key

i manged to install traefik in the demo1 cluster but the above fail 

PS C:\openflow\0.1.66\openflow> helm install openflow openiap/openflow -n demo1 --values ./demo.yaml
Error: INSTALLATION FAILED: template: openflow/templates/zipkin.yaml:2:18: executing "openflow/templates/zipkin.yaml" at <.Values.openflow.license_key>: nil pointer evaluating interface {}.license_key
PS C:\openflow\0.1.66\openflow>

**Comment by skadefro** [comment]
Someone else mentioned this on rocket chat. I cannot reproduce it, but we managed to solve it for him, but adding an empty license_key value under the openflow leaf.
So from the example  it would look like this
```
# this will be the root domain name hence your openflow url will now be http://demo.mydomain.com 
domainsuffix: mydomain.com # this will be added to all domain names
domain: demo 
# if using a reverse procy that add ssl, uncomment below line.
# protocol: https
openflow:
  license_key:
#  external_mongodb_url: mongodb+srv://user:pass@cluster0.gcp.mongodb.net?retryWrites=true&w=majority
rabbitmq:
  default_pass: supersecret
# if you are using mpongodb atlas, or has mongodb running somewhere else
# uncomment below line, and external_mongodb_url in openflow above
# mongodb:
#   enabled: false
```
